[font]
size = 10.3

[font.normal]
family = "BerkeleyMono Nerd Font Mono" 

[font.bold]
family = "BerkeleyMono Nerd Font Mono" 

[font.italic]
family = "BerkeleyMono Nerd Font Mono" 

[font.bold_italic]
family = "BerkeleyMono Nerd Font Mono" 

[window]
decorations = "None"
opacity = 0.8
blur = true
dynamic_padding = true

[window.padding]
x = 10
y = 16


