-- Parses ../colors/matugen.conf (still in hyprlang $var syntax, regenerated by matugen)
-- and exposes the color values as a Lua table.
--
-- Matugen owns colors/matugen.conf, so we read it as-is at config load time.

local M = {}

local config_dir = os.getenv("HOME") .. "/.config/hypr"
local matugen_path = config_dir .. "/colors/matugen.conf"

local f = io.open(matugen_path, "r")
if f then
    for line in f:lines() do
        -- Match: $name = value
        local name, value = line:match("^%s*%$([%w_]+)%s*=%s*(.-)%s*$")
        if name and value and value ~= "" then
            M[name] = value
        end
    end
    f:close()
else
    io.stderr:write("[hyprland.lua] WARN: could not read " .. matugen_path .. "\n")
end

return M
