###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = pkill rofi || $HOME/.config/rofi/launchers/type-7/launcher.sh
$logout_menu = wlogout -b 5 -T 400 -B 400
$wallpaper_menu = $HOME/.local/bin/chwal
$wallpaper_menu_mine = $HOME/.local/bin/chwal-me
$theme_menu = $HOME/.local/bin/chthm
$toggle_notifications = swaync-client -t -sw
$task_menu = $HOME/.local/bin/done-task-menu
$toggle_look = $HOME/.local/bin/toggle-decoration
$new_note = $HOME/.local/bin/add-note
$open_work_apps = $HOME/.local/bin/open-work-apps
$toggle_wallpaper_cycle = if [ $(cat $HOME/.local/state/cycle_wallpaper) == "1" ]; then echo "0" > $HOME/.local/state/cycle_wallpaper; notify-send "Wallpaper Cycle Turned Off"; else echo "1" > $HOME/.local/state/cycle_wallpaper; notify-send "Wallpaper Cycle Turned On"; fi
$screen_ocr = $HOME/.local/bin/read-screen
