monitor=DP-3,2560x1440,0x0,1
monitor=DP-2,2560x1440,2560x0,1
workspace=1,monitor:DP-3,defaultName:Browser
workspace=2,monitor:DP-3,defaultName:Communication
workspace=3,monitor:DP-3,defaultName:Meeting 
workspace=4,monitor:DP-2,defaultName:Terminal
workspace=5,monitor:DP-2,defaultName:Notes
workspace=6,monitor:DP-2,defaultName:Extra
