
workspace=1,monitor:DP-1,defaultName:Browser
workspace=2,monitor:DP-1,defaultName:Communication
workspace=3,monitor:DP-1,defaultName:Meeting 
workspace=4,monitor:DP-2,defaultName:Terminal
workspace=5,monitor:DP-2,defaultName:Notes
workspace=6,monitor:DP-2,defaultName:Extra
