#!/usr/bin/bash

if [[ -z $(pgrep -x "firefox") ]]
then
				firefox  &
fi
if [[ -z  $(pgrep -x "thunderbird") ]]
then
				thunderbird  &
fi
if [[ -z $(pgrep -x "obsidian") ]]
then
				obsidian &
fi

slack  &
