#!/usr/bin/bash

resp=$(curl http://dev.joaoporta.tech:8080/timetracker -s)

isworking=$(echo $resp | jq .IsWorking -r)
total=$(echo $resp | jq .TotalToday -r)

if [ $isworking = "true" ]; then
				class='"working"'
else
				class='"not-working"'
fi
    echo "{\"text\":\"$total\",\"class\":$class}"
